### ISSUE TITLE
Move Go Services to Travis

### ISSUE THREAD

**Issue by pjnorton** [mistifyio/mistify#16]
Move all Go services to Travis.  I think that's about it.  Possibility that this may need to be an epic with each Go service as a separate card but I leave that to smarter people to determine.
- [ ] mistifyio/mistify-agent-image#41
- [x] mistifyio/mistify-agent-libvirt#23
- [x] mistifyio/go-zfs#38
- [x] mistifyio/gozfs#18
- [x] mistifyio/lochness#123
- [x] mistifyio/mistify-agent#52
- [x] mistifyio/mistify-agent-docker#20
- [x] mistifyio/mistify-image-service#12

**Comment by joshie** [comment]
Let's create issues in the repositories for go products we care about and link them here.
