### ISSUE TITLE
Container Security

### ISSUE THREAD

**Issue by pjnorton** [mistifyio/mistify#33]
# Issues Contained in this Epic
- [ ] #34 Investigate Whitelist Approaches for Container Security
- [ ] #41 Base Security Profile
- [ ] #42 Investigate System Call Auditing
# Epic Description

Epic for tasks related to container security.  Lots of sub-tasks going to be here.
